### ISSUE TITLE
Basic Macro Failure?

### ISSUE THREAD

**Issue by vshesh** [Gozala/wisp#123] opened 2015-06-01 08:49 UTC
Some very simple macros fail to compile in both the REPL and from source and in the try-wisp website.

I can get this working in Clojure/CLJS so I know that the syntax should be correct:

```clojure
(defmacro incc [c] (+ c 1))
(incc 1)
; should produce 2, but it gives me nothing
(+ 1 (incc 1)) 
; should produce 3, but gives me nothing.
```

On the repl if I try, I get
```clojure
=> (defmacro incc [c] (+ c 1))
=> (incc 1)
TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (native)
    at withMeta (/Users/Vishesh/repos/dng3/node_modules/wisp/ast.js:35:16)
    at /Users/Vishesh/repos/dng3/node_modules/wisp/expander.js:73:30
    at expand (/Users/Vishesh/repos/dng3/node_modules/wisp/expander.js:74:7)
    at /Users/Vishesh/repos/dng3/node_modules/wisp/expander.js:176:33
    at macroexpand1 (/Users/Vishesh/repos/dng3/node_modules/wisp/expander.js:177:11)
    at loop (/Users/Vishesh/repos/dng3/node_modules/wisp/expander.js:183:30)
    at macroexpand (/Users/Vishesh/repos/dng3/node_modules/wisp/expander.js:188:11)
    at /Users/Vishesh/repos/dng3/node_modules/wisp/analyzer.js:597:31
    at analyzeList (/Users/Vishesh/repos/dng3/node_modules/wisp/analyzer.js:601:11)
```
What is going on? The documentation seems to suggest that macros are fully powered, and the chain example works on all of the platforms, so I can't understand why something like this would fail.

I figured it could be because + is a special form instead of a function or something, so I tried another very simple situation (and again, it works in CLJS/Clojure and even Hy, a python lisp) 
```clojure
(defmacro mapify [vecs] (reduce (fn [m item] (assoc m (first item) (second item))) vecs))
; should replace a literal constant of vectors like [["key" 1] ["key2" 2] ...] -> {"key" 1 "key2" 2} 
; i get nothing.
```
Again, the REPL won't even let me finish entering this, it keeps requesting more input.

**Comment by Gozala** [comment] 2015-06-01 18:18
@vshesh this is known issue and has to do with a result of the macro being a primitive value vs being a list form. That is also why you see "Object.defineProperty called on non-object" message, macro expander tries to attach a metadata to the expaneded form and it fails to do so if the form is primitive. This is the line where the issue occurs:
https://github.com/Gozala/wisp/blob/0bcaeb6376086314a13b51a3c7b5ac507f5209f9/src/expander.wisp#L33

I have being worknig on support for adding metadata to primitives, but until that's fixed best fix way to go about it would be to check if `expansion` is primitive and skip adding metadata in such case.

**Comment by Gozala** [comment] 2015-06-01 18:19
@vshesh would you be willing to give that a try ?

**Comment by Gozala** [comment] 2015-06-01 18:20
This is duplicate of #121 let's continue discussing this there

**Closed by Gozala** 2015-06-01 18:20 UTC
